### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by mbuhot** [ananthakumaran/xlsx_stream#1]
Hi,

Thanks for creating `xlsx_stream`, this looks really useful for me as I have a reports generations processing getting killed by OutOfMemory using `elixlsx` to build the file 👍 

Could you please add a License file to the repo? 
I saw it is MIT in the package metadata, but having the MIT license in the repo would clarify.

Thanks again!

**Comment by ananthakumaran** [comment]
done. I will try to put together a proper README file, but this library is much more lower level than other libraries that create xlsx files, the value added here is very small and most of the work is done by xml_stream & zstream library. You need to be somewhat familiar with the xlsx specification. On the plus side, anything that can be done could be done via this approach. Custom styles etc could be easily added. Yes and this library is precisely written because we can't afford to keep everything in memory. Look at test files for example

**Comment by mbuhot** [comment]
Thanks! Looking forward to the README, but the test looks like it shows how to get the complete file working 👍
